import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import '../cubit/pairing_cubit.dart';
import '../cubit/pairing_state.dart';

/// The pairing ceremony UI page.
///
/// State machine:
/// - [PairingIdle]         → "Pair with a System" button
/// - [PairingScanning]     → QR camera scanner
/// - [PairingTokenScanned] → system detail confirmation screen
/// - [PairingInProgress]   → loading indicator
/// - [PairingSuccess]      → navigate to /dashboard
/// - [PairingError]        → SnackBar + return to Idle
class PairingPage extends StatelessWidget {
  const PairingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<PairingCubit, PairingState>(
      listener: (context, state) {
        if (state is PairingSuccess) {
          Navigator.of(context).pushReplacementNamed('/dashboard');
        } else if (state is PairingError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(state.message)),
          );
        }
      },
      builder: (context, state) {
        return Scaffold(
          appBar: AppBar(title: const Text('Pair with a System')),
          body: _buildBody(context, state),
        );
      },
    );
  }

  Widget _buildBody(BuildContext context, PairingState state) {
    if (state is PairingScanning) {
      return _ScannerView(
        onDetect: (rawValue) =>
            context.read<PairingCubit>().onQrScanned(rawValue),
      );
    }

    if (state is PairingTokenScanned) {
      final token = state.token;
      return Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Confirm Pairing',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 24),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _row('System', token.systemLabel),
                    const Divider(),
                    _row('Endpoint', token.pairingEndpoint),
                    const Divider(),
                    _row(
                      'Capabilities',
                      token.capabilities.isEmpty
                          ? 'None'
                          : token.capabilities.join(', '),
                    ),
                  ],
                ),
              ),
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: () => context.read<PairingCubit>().confirmPairing(),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
              ),
              child: const Text('Confirm and Pair'),
            ),
            const SizedBox(height: 12),
            OutlinedButton(
              onPressed: () => context.read<PairingCubit>().startScanning(),
              child: const Text('Scan Again'),
            ),
            const SizedBox(height: 24),
          ],
        ),
      );
    }

    if (state is PairingInProgress) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 16),
            Text('Pairing with system...'),
          ],
        ),
      );
    }

    // PairingIdle (default)
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.qr_code_scanner, size: 80, color: Colors.grey),
            const SizedBox(height: 24),
            const Text(
              'No systems paired yet.',
              style: TextStyle(fontSize: 18),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            const Text(
              'Scan a QR code generated by your backend system to begin.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 32),
            ElevatedButton.icon(
              onPressed: () => context.read<PairingCubit>().startScanning(),
              icon: const Icon(Icons.qr_code),
              label: const Text('Pair with a System'),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 14,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _row(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 100,
            child: Text(
              label,
              style: const TextStyle(
                fontWeight: FontWeight.bold,
                color: Colors.grey,
              ),
            ),
          ),
          Expanded(child: Text(value)),
        ],
      ),
    );
  }
}

class _ScannerView extends StatefulWidget {
  final void Function(String rawValue) onDetect;

  const _ScannerView({required this.onDetect});

  @override
  State<_ScannerView> createState() => _ScannerViewState();
}

class _ScannerViewState extends State<_ScannerView> {
  bool _scanned = false;

  @override
  Widget build(BuildContext context) {
    return MobileScanner(
      onDetect: (capture) {
        if (_scanned) return;
        final barcodes = capture.barcodes;
        if (barcodes.isEmpty) return;
        final raw = barcodes.first.rawValue;
        if (raw == null || raw.isEmpty) return;
        _scanned = true;
        widget.onDetect(raw);
      },
    );
  }
}
