name: sms_sender
description: Local SMS sender plugin for background isolate execution.
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.superadmin.sms_sender
        pluginClass: SmsSenderPlugin
